### ISSUE TITLE
Add Factory Pattern for Linkdrop Contracts

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#11]
# Description
Implement the Factory pattern for Linkdrop Contract deployment. 
The Factory contract should have the MasterCopy contract (library) and proxies (clones) that inherit logic from the MasterCopy. Similar to https://eips.ethereum.org/EIPS/eip-1167. 

Clones (or proxies) should be created using[ the CREATE2 opcode](https://github.com/ethereum/EIPs/pull/1014) so that the address of the contract can be precomputed before deployment. Here's a useful code to precompute address - https://github.com/miguelmota/solidity-create2-example

A similar technique was implemented in Daily Wallet. 
Factory Contract - https://github.com/dailywallet/gasless-webwallet/blob/master/universal-login-contracts/contracts/IdentityFactory.sol

# Subtasks included
- [x] Factory contract
- [x] Proxy delegation to the MasterCopy
- [x] Address of the proxy contract can be precomputed (CREATE2)
- [x] Tests

# Definition of done
All subtasks are implemented.

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
Implemented in #13  Run ```npx waffle``` and ```yarn test test/Proxy.js  ```

**Comment by Dobrokhvalov** [comment]
@amiromayer As the approach chosen in #13 is 2-3 times more expensive than the ERC-1167 approach, I've closed the #13 PR. Please implement the scope of this issue in the ERC-1167 way

**Comment by amiromayer** [comment]
@Dobrokhvalov Check #14

**Comment by Dobrokhvalov** [comment]
👍
