### ISSUE TITLE
Handle errors coming from server

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#111]
# Description
Right now when submitting invalid transactions, server responses with the same error. Make sure it responses with understandable and proper error messages and make sure SDK returns errors as well.

# Subtasks included

- [x] Change server logic, so that it responses with error messages
- [x] Change SDK logic, so that it returns errors

# Definition of done
Server responses with error messages when passing invalid params, SDK returns errors

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
Implemented in https://github.com/LinkdropProtocol/linkdrop-monorepo/pull/119
