### ISSUE TITLE
Change factory contract

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#115]
# Description
Add the ability to check whether a link has been claimed from the factory contract.

# Subtasks included

- [x] Add new functionality
- [x] Test new functionality with waffle

# Definition of done
New tests are passed

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
implemented in https://github.com/LinkdropProtocol/linkdrop-monorepo/pull/118
