### ISSUE TITLE
Check whether all params are passed to SDK

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#116]
# Description
Currently SDK constructs a link assuming that all params are passed to `generateLink` function. Check this and throw error if something is missing.

# Subtasks included

- [x] Add params validation

# Definition of done
SDK throws error if one or more params are missing

# Reviewer
@Dobrokhvalov @spacehaz

**Comment by Dobrokhvalov** [comment]
Implemented in https://github.com/LinkdropProtocol/linkdrop-monorepo/pull/117
