### ISSUE TITLE
Update SDK

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#131]
# Description
Update SDK so that it supports new contracts' functionality (ETH + ERC20 | ETH + ERC721)

# Subtasks included

- [x] Update SDK
- [x] Test and make sure SDK works

# Definition of done
SDK supports new contracts' functionality (ETH + ERC20 | ETH + ERC721)

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
New functionality is (ETH + ERC20 | ETH + ERC721), right?

**Comment by amiromayer** [comment]
@Dobrokhvalov Yep

**Comment by amiromayer** [comment]
Implemented in #142
