### ISSUE TITLE
Contract Upgradability Research

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#138]
# Description
As a user, I'd like to have an option to upgrade my proxy contract if current proxy missing some functionality. 

The problem with our current approach is that it doesn't allow users to upgrade deployed proxies. 

Research a way to provide upgradability to our users with the following properties: 
- [x] Cheap deploy cost for new proxies (similar to [eip-1167)]( https://eips.ethereum.org/EIPS/eip-1167) 
- [x] Proxies should be upgradable only by users 

Some projects tackling a similar issue in the space: 
- Universal Logins - https://github.com/UniversalLogin/UniversalLoginSDK/tree/master/universal-login-contracts/contracts/erc1836
- Gnosis Safe - https://github.com/gnosis/safe-contracts
- Argent - https://github.com/argentlabs/argent-contracts/tree/develop/contracts/wallet

# Definition of done
Proposal for Upgradability Framework for Linkdrop Contracts

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
An idea for inspiration - https://blog.ricmoo.com/wisps-the-magical-world-of-create2-5c2177027604

**Comment by amiromayer** [comment]
I propose to take a look at [pattern](https://etherscan.io/address/0x0A6d9D8e98146d5c36ef97C752DF215854573536#code), Metacash is using: https://medium.com/lamarkaz/dai-in-the-hands-of-all-8ed335879ae9
