### ISSUE TITLE
Text edits for linkdrop demo app

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#158]
# Description

## 1. Text edit

![Screen Shot 2019-05-17 at 12 34 13 PM](https://user-images.githubusercontent.com/18598519/57951838-2ad1be00-78a0-11e9-8406-a70c76923104.png)

**Fix by:**

- [x] This demo-app is only fit to be used on the Ethereum Rinkeby testnet

## 2. Text edit

![Screen Shot 2019-05-17 at 12 46 31 PM](https://user-images.githubusercontent.com/18598519/57952395-efd08a00-78a1-11e9-88ea-48ceb3ecd96a.png)

**Fix by:**

- [x] Linkdrop is only supported on Rinkeby testnet until the **Bug Bounty** has concluded. 

## 3. Text edit

![IMAGE 2019-05-17 12:32:20](https://user-images.githubusercontent.com/18598519/57951732-d0d0f880-789f-11e9-8eec-c539e237b50e.jpg)

- [x] Send digital assets encoded in links

## 4. Edit

![IMAGE 2019-05-17 12:32:28](https://user-images.githubusercontent.com/18598519/57951742-d62e4300-789f-11e9-8055-ac97b55a3f27.jpg)

**Fix by:**

- [x] Request early access to the Linkdrop Dashboard

## 5. Edit

![IMAGE 2019-05-17 12:32:49](https://user-images.githubusercontent.com/18598519/57951758-e21a0500-789f-11e9-9588-a029d6dfa0be.jpg)

**Fix by:**

- [x] Scan or copy to send digital assets

- [x] Change "Rinkeby Network" to "Rinkeby testnet"

**Comment by artignatyev** [comment]
All good, I assign @spacehaz to do that. Also, mockups are updated too
