### ISSUE TITLE
ETH Linkdrop Deployment via Terminal

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#18]
# Description
In order to make testing and integrating front-end with back-end easier, add linkdrop deployment scripts, so that it's possible to deploy linkdrop campaigns and generate claim links via command line. 

Script source files should be in the ‘scripts’ folder

**Configs** 
The config file (the same as in https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/16) should contain the following params under `linkdrop` key:  
- `senderPrivateKey`: sender's private key, the sender should have positive token balance in order to deploy a linkdrop 
- `amount`: the number of ETH per link 
- `factoryAddress`: address of the Factory Contract
- `linksNumber`: number of links to generate 
- `networkId`: Ethereum network id, e.g. "1"  for Mainnet
- `jsonRpcUrl`: Url of JSON-RPC provider

**Commands**
`yarn linkdrop eth`
The command: 
- precomputes proxy address using CREATE2 
- transfers ETH needed (according to linkdrop params) from senders to the proxy address
- generates links in a CSV file `scripts/output/links-eth.csv` 

**Meaningful Errors**
Failed command execution, should display meaningful errors in the following cases:  
- Factory Contract isn't deployed
- Sender address doesn't have enough ETH to deploy linkdrop

# Subtasks included
- [x] Example config for a test network (e.g. `config.json.rinkeby`)
- [x] Deploy ETH Linkdrop command

# Definition of done
Valid claim links with ETH can be generated using terminal commands.  

# Dependency
The command for Factory Deployment should be implemented first -https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/22

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
@Dobrokhvalov Done in #26

**Comment by Dobrokhvalov** [comment]
@amiromayer Good job! Merge #26, but you forgot to transfer ETH to the proxy address: 

> transfers ETH needed (according to linkdrop params) from senders to the proxy address

Please open new PR with the fix

**Comment by Dobrokhvalov** [comment]
Fixed in #45
