### ISSUE TITLE
Factory Contract Deployment via Terminal

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#22]
# Description
In order to make testing and integrating front-end with back-end easier, add linkdrop deployment scripts, so that it's possible to deploy linkdrop campaigns and generate claim links via command line. 

Script source files should be in the ‘scripts’ folder

**Configs** 
The config file (the same as in https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/16) should contain the following params under `linkdrop` key:  
- `senderPrivateKey`: sender's private key, the sender should have positive token balance in order to deploy a linkdrop 
- `networkId`: Ethereum network id, e.g. "1"  for Mainnet
- `jsonRpcUrl`: Url of JSON-RPC provider

**Command**
`yarn deployFactory`
Script deploys Factory on the Ethereum network defined in the configs. 

**Output**
Script updates the config file with the address of the deployed Factory Contract.

**Errors**
Failed command execution, should display meaningful errors in the following cases:  
- Sender address doesn't have enough ETH to deploy Factory Contract

# Subtasks included
- [ ] Example config for a test network (e.g. `config.json.rinkeby`)
- [ ] Deploy Factory command

# Definition of done
Factory Contract can be deployed using terminal command.  

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
Done in #29
