### ISSUE TITLE
Add additional check to Dashboard contracts

### ISSUE THREAD

**Issue by amiromayer** [LinkdropProtocol/linkdrop-monorepo#283]
# Description
Currently we check allowance in contracts, while not checking that sender owns neccessary tokens at the time of claim. 
Add new checks that cover this issue.

# Subtasks included

- [ ] Add additional balance check
- [ ] Test new functionality

# Definition of done
All tests are passing

# Reviewer
@Dobrokhvalov

**Comment by Dobrokhvalov** [comment]
Implemented in #286
