### ISSUE TITLE
Defining technical milestones for the Demo Day

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#33]
# Description
Prepare a plan for technical milestones for the Demo Day, so that the progress can be tracked and we can make sure that we are on track before the demo day 

# Subtasks included

- [x] Technical plan with assignees and dates for deliveries

# Definition of done
The complete technical plan is done

# Reviewer
@Kisgus @artignatyev

**Comment by Kisgus** [comment]
Based on above the milestones are being updated. Demo-day = Linkdrop demo release milestone.

**Comment by Dobrokhvalov** [comment]
We agreed to have 2 milestones: 
 -  Linkdrop demo release (by 6th May) - https://github.com/LinkdropProtocol/linkdrop-monorepo/milestone/1
 - Linkdrop PRO release (by 20th May) - https://github.com/LinkdropProtocol/linkdrop-monorepo/milestone/2 

**Demo release (by 6th May)**
In order to achieve first milestone, I propose to implement the following tasks: 
- Finish the claim page (@amiromayer?) - #65
- Setup linkdrop relayer (@amiromayer) - #62 
- Send demo + landing (@spacehaz) - #56 
- Host front-end apps -  #66
- Blog post + FAQ (@seichris ?) - #63, #64 
- Technical description (@Dobrokhvalov ) - #42 
- Legal docs ready (@Kisgus) - #46
