### ISSUE TITLE
Linkdrop Technical Description

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#42]
# Description
Technical Description for the Linkdrops.

# Subtasks included
Technical description of the scheme:
- [x] Linkdrop flow
- [x] CREATE2 UX improvements

# Definition of done

Completed subtasks

# Reviewer
@Kisgus

**Comment by Kisgus** [comment]
Anything I can help with? I'm out of tasks :)

**Comment by Dobrokhvalov** [comment]
Will make a separate issue for the upgradability post
