### ISSUE TITLE
ETH Linkdrop claim via terminal

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#47]
# Description
Add a script and command to claim ETH via end-point call implemented in https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/16  

**Configs** 
Receiver address should be defined in the config file. 

# Subtasks included
- [ ] Claim ETH script and command 

# Definition of done
Linkdrop can be claimed using terminal command.  **Links should be claimed via server call**

# Dependency
ETH claim server end-point -  https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/16

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
Implemented in #51
