### ISSUE TITLE
Linkdrop Dashboard & Analytics mockups

### ISSUE THREAD

**Issue by artignatyev** [LinkdropProtocol/linkdrop-monorepo#50]
# Description

Mockups of Dashboard where user can create and set up Linkdrop campaign and see analytics. Also, mockups of Sign Up / Login's user flow.

# Subtasks included

- [x] Linkdrop Sign up / Log In flow
- [ ] Linkdrop Dashboard and Campaign creation flow
- [ ] Linkdrop Analitycs (#24)

# Definition of done

Above screens are done, fully handed-over, and the implementation has started.

# Reviewer

@Dobrokhvalov, @Kisgus

**Comment by Kisgus** [comment]
I would propose to split Analytics into a dedicated issue

**Comment by Kisgus** [comment]
I propose to split Analytics into a dedicated issue

**Comment by Kisgus** [comment]
Excluding analytics
