### ISSUE TITLE
Implement Linkdrop Contract

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#6]
# Description
Basic ERC20 and ether implementation for linkdrops. 
No need for ERC721 yet. 

# Subtasks included

- [x] ERC20 support
- [x] ether support 
- [x] tests

# Definition of done
- Has all functions implemented from ILinkdrop and functionality is fully tested

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
Completed in #8
