### ISSUE TITLE
Linkdrop Website for Demo day

### ISSUE THREAD

**Issue by artignatyev** [LinkdropProtocol/linkdrop-monorepo#61]
# Description

Mockups for a landing page with other pages for a website.

# Subtasks included

- [x] Main page (landing)
- [x] Product page
- [ ] About page

# Definition of done

Above screens are done, fully handed-over, and the implementation has started.

# Reviewer

@Dobrokhvalov, @Kisgus

**Comment by Kisgus** [comment]
Done
