### ISSUE TITLE
Prepare the launch blog post for Linkdrop 

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#63]
# Description
Prepare the launch blog post for Linkdrop. 

# Subtasks included
- [ ] Define what should be in the blog post
- [ ] write the blog post

# Definition of done
We have the blog post ready for the launch.  

# Reviewer
@Kisgus

**Comment by Kisgus** [comment]
Please pm me the current version @seichris
