### ISSUE TITLE
Prepare a doc with questions and answers for the FAQ page

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#64]
# Description
Before releasing the demo, it would be good to have a page with info about security, technical questions and how to use our solution in Q&A format

# Subtasks included
- [x] Define questions
- [x] Answer the questions

# Definition of done
The first version of FAQ is written with questions and answers in a doc

# Reviewer
@Kisgus

**Comment by seichris** [comment]
[the doc](https://docs.google.com/document/d/1Mfoqc6OzEDETkLKaJReFvCF0ReNu0eQVRiVOFTOhVTQ/edit#)

**Comment by seichris** [comment]
first draft of the faq in the wiki: https://github.com/LinkdropProtocol/linkdrop-monorepo/wiki/Frequently-Asked-Questions

**Comment by Kisgus** [comment]
Reviewed and edited a bit. The first version is considered done. Thanks :)

**Comment by Kisgus** [comment]
Future enhancements to keep in mind @seichris 

- Mock-ups of how the flow looks, once linkdrop.io is made public
- Mock-ups of how it technically works, once the linkdrop.io blogpost is public
