### ISSUE TITLE
Prepare contracts for the external auditors and bug bounty

### ISSUE THREAD

**Issue by Dobrokhvalov** [LinkdropProtocol/linkdrop-monorepo#76]
# Description
We need to have our code audited and place a bug bounty to make our code more secure. 

# Subtasks included
- [x] Comments for all the contract functions 
- [x] Make sure that all external functions are covered with tests 

The contract code should be commented in a similar way as in https://github.com/VolcaTech/cryptoxmas.xyz/blob/master/cryptoxmas-contracts/contracts/CryptoxmasEscrow.sol#L86 

# Definition of done
Code is ready for the review. 

# Reviewer
@Dobrokhvalov

**Comment by amiromayer** [comment]
Done in #82
