### ISSUE TITLE
List of Biz tasks for Demo-Day 22nd of May

### ISSUE THREAD

**Issue by Kisgus** [LinkdropProtocol/linkdrop-monorepo#78]
# Description

Below tracks biz related tasks and open-questions for tachyon demo-day, in addition to #33 

# Linkdrop.org

- [x] Do we need any changes to this website?

# Linkdrop.io

- [x] FAQ

- [x] Team pictures, links and description

- [x] Referral / quotes from 2 customers / users

- [x] A few logos of projects using the Linkdrop Protocol

- [x] "Powered by Linkdrop Protocol" text with link to Linkdrop.org website

- [x] A small demo-video of the send / receive flow of Linkdrop DEMO

# 4-min demo deck

- [x] Opportunity, problem/solution, traction and ask

- [ ]  A small demo-video of the send / receive flow of Linkdrop DEMO

# Extended seed deck

- [x]  Full seed deck only given in person to investors

# Reviewer

@Dobrokhvalov @artignatyev @Kisgus

**Comment by seichris** [comment]
Let's concentrate on the Linkdrop.io demo site. Mockups are in the usual file.
Demo deck and video we will work on on wednesday.

**Comment by Kisgus** [comment]
#99 Above elements are considered the enhancements to the website public announced the 13th.
These enhancements needs to be ready before the demo-day the 22th of May.

**Comment by Kisgus** [comment]
Also included tasks as defined in #80 

- [ ] Telegram message
- [ ] Product Feedback Repo
- [ ] Termsheet v1
- [ ] European setup

**Comment by Kisgus** [comment]
Website and termsheet, not live, rest is done
