### ISSUE TITLE
Plan regular communication with the community

### ISSUE THREAD

**Issue by seichris** [LinkdropProtocol/linkdrop-monorepo#80]
# Description

Proposed framework and next steps are in here:
https://docs.google.com/document/d/186I4cfQJxX7M-oZwOzYvEfo6ZXeNxBGkbr9BPQDP4ek/edit

# Starting with 

- [x] https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/64
- [x] https://github.com/LinkdropProtocol/linkdrop-monorepo/issues/63
- [x] Draft community plan, this issue 

# Definition of done

Done, when the framework is fixed

# Reviewer
@Kisgus

**Comment by Kisgus** [comment]
Done and agreed
