### ISSUE TITLE
Linkdrop.io website mockups for 13th May soft launch

### ISSUE THREAD

**Issue by artignatyev** [LinkdropProtocol/linkdrop-monorepo#99]
# Description

Mockups of Linkdrop.io website for 13th May soft launch.

# Subtasks included

- [x] Final mockups
- [x] Text and wording checks
- [x] Polishing

# Definition of done

Above screens are done, fully handed-over, and the implementation has started.

# Reviewer

@Dobrokhvalov, @Kisgus

**Comment by Kisgus** [comment]
The v1 mock-ups looks good to me and are ready to be implemented. If the same goes for you @Dobrokhvalov please feel free to close this issue.
